Page({
  onShareAppMessage: function () {
    return {
      title: "分享给好友",
      path: "/pages/index/index", // 分享的路径
      image: "../../images/logo.png", // 分享的图片
    };
  },
  onReady: function () {
    this.getLocation();
  },
  data: {
    latitude: "",
    longitude: "",
    scale: 15,
    buttons: [{ text: "取消" }, { text: "确认" }],
  },
  getLocation: function () {
    wx.getLocation({
      type: "wgs84",
      success: (res) => {
        console.log("定位成功", res);
        this.setData({
          latitude: res.latitude,
          longitude: res.longitude,
          markers: [
            {
              id: 1,
              latitude: 32.0896,
              longitude: 118.848,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "南京抗日航空烈士纪念馆",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 2,
              latitude: 31.973,
              longitude: 118.762,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "南京民间抗日战争博物馆",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 3,
              latitude: 32.04285,
              longitude: 118.8015,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "中国代表团，梅园新村",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 4,
              latitude: 32.062,
              longitude: 118.766,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "颐和路社区将军馆",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 5,
              latitude: 32.1196,
              longitude: 118.6927,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "江北新区红色广场",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 6,
              latitude: 32.0964,
              longitude: 118.7214,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "浦口火车站",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },

            {
              id: 7,
              latitude: 32.457,
              longitude: 118.933,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "桂子山烈士陵",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 8,
              latitude: 32.117,
              longitude: 118.771,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "侵华日军南京大屠杀草鞋峡遇难同胞纪念碑",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 9,
              latitude: 32.1248,
              longitude: 118.6935,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "南京工运纪念馆",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 10,
              latitude: 32.0648,
              longitude: 118.7827,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "八路军驻京办事处纪念馆",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 11,
              latitude: 32.0038,
              longitude: 118.7792,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "雨花台烈士陵园",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 12,
              latitude: 32.1212,
              longitude: 118.81,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "晓庄革命烈士纪念碑",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 13,
              latitude: 31.9857,
              longitude: 118.7714,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "皖南事变三烈士墓",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 14,
              latitude: 32.1273,
              longitude: 118.6431,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "浦口革命烈士纪念碑",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 15,
              latitude: 32.5328,
              longitude: 118.6724,
              width: 40,
              height: 40,
              iconPath: "/images/position.png",
              callout: {
                content: "竹镇市抗日民主政府旧址",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
            {
              id: 16,
              latitude: res.latitude,
              longitude: res.longitude,
              iconPath: "/images/my_position.png",
              width: 40,
              height: 40,
              callout: {
                content: "你所在的位置",
                color: "#FFFFFF",
                fontSize: 10,
                borderRadius: 10,
                bgColor: "#FF4500",
                padding: 10,
                display: "ALWAYS",
              },
            },
          ],
        });
      },
      fail: (err) => {
        console.error("定位失败", err);
      },
    });
  },
  goToSearch: function () {
    wx.navigateTo({
      url: "/pages/subpages/search/search",
    });
  },
});
